### PR TITLE
MM-32516: selectively align profile selector to right

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
To facilitate using the profile selector with the new "assignee" button, a `right: 0` property was unconditionally added. Unfortunately, this shifted all the profile selectors as such, causing problems for the commander dropdown when the RHS shrinks in size for smaller windows:

image

image

image

As a workaround, pass in a new `showOnRight` prop to conditionally set
this field:

image

image

image

image

Ideally, we'll revisit this component in the future.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-32516

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
This feels... ugly. But I guess we need it.

**Review by crspeller — APPROVED** [review]
Needs more CSS magic.

**Review by prapti — APPROVED** [review]
The commander dropdown no longer renders behind the main channel. Tested and verified in all three major browsers and desktop app.
Approving.

**Pull request merged**
