### PR TITLE
Change the text of the ephemeral message from "You can only show..." to "You can only see..."

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary
Change the text of the ephemeral message from "You can only show..." to "You can only see..." in command.go

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/16423

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Comment by lieut-data** [comment]
Thanks, @haardikdharma10 (and @jfrerich!)

**Review by cpoile — APPROVED** [review]
Thanks @haardikdharma10 !

**Comment by haardikdharma10** [comment]
Hi @prapti, can you take a look at the changes and confirm whether the PR is ready to merge? Thanks:)

**Review by prapti — APPROVED** [review]
The changes look good! Thank you for help on this @haardikdharma10 🎉 
Approving.

**Pull request merged**
