### PR TITLE
MM-31234: remove reminder post on end

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
If there is an outstanding reminder post in the incident channel, remove it on ending the incident.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31234

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Looks great! 
(I shouldn't have missed that the first time around, but I like the new tests, thank you.)

**Comment by lieut-data** [comment]
@prapti, I may decide to merge this today in advance of all dev reviews. Did you want to review this pre-merge?

**Comment by prapti** [comment]
@lieut-data I can do a quick sanity test on this PR right now.

**Review by prapti — APPROVED** [review]
Looks good to me @lieut-data. Thank you for the heads up!

**Pull request merged**
